services:
  frontend:
    build:
      context: front_end
    ports:
      - "8501:8501"
    depends_on:
      - chroma  
    env_file:
      - .env 
    networks:
      - my-network  
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./chroma_database:/data 
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  chroma_database:
    